/**
 * PDF Generator for FutureMap Career Roadmaps
 * 
 * Generates a premium, corporate-report-style PDF containing
 * a user's complete personalized career roadmap.
 */
import { jsPDF } from 'jspdf'

// ─── Types ───────────────────────────────────────────────────────────

export interface RoadmapPDFData {
  // User info
  userName: string
  userEmail: string

  // Roadmap meta
  roadmapId: string
  title: string
  description: string
  careerGoal: string
  currentLevel: string
  durationMonths: number
  progress: number
  generatedDate: string

  // Phases
  phases: PDFPhase[]

  // AI enrichments (optional — gracefully degrade if missing)
  executiveSummary?: string
  currentSkills?: string[]
  missingSkills?: string[]
  readinessScore?: number
  recommendedResources?: PDFResource[]
  projectRecommendations?: PDFProjectGroup[]
  careerOpportunities?: PDFCareerOpportunity[]
  aiRecommendations?: string[]
}

export interface PDFPhase {
  title: string
  description: string
  duration: string | number
  type?: string
  nodes?: PDFNode[]
}

export interface PDFNode {
  title: string
  type?: string
  description?: string
  duration?: string
  difficulty?: string
  resources?: string[]
  skills?: string[]
}

export interface PDFResource {
  name: string
  platform: string
  difficulty: string
  duration: string
}

export interface PDFProjectGroup {
  level: string
  projects: string[]
}

export interface PDFCareerOpportunity {
  role: string
  salaryRange?: string
  demand?: string
  growth?: string
}

// ─── Color Palette (FutureMap Branding) ──────────────────────────────

const COLORS = {
  // Primary brand
  primaryDark: [15, 23, 42] as [number, number, number],       // Slate-900
  primaryMid: [30, 41, 59] as [number, number, number],        // Slate-800
  primaryLight: [51, 65, 85] as [number, number, number],      // Slate-700

  // Accent
  accentCyan: [6, 182, 212] as [number, number, number],       // Cyan-500
  accentPurple: [139, 92, 246] as [number, number, number],    // Violet-500
  accentPink: [236, 72, 153] as [number, number, number],      // Pink-500

  // Functional
  white: [255, 255, 255] as [number, number, number],
  textPrimary: [15, 23, 42] as [number, number, number],
  textSecondary: [100, 116, 139] as [number, number, number],  // Slate-500
  textMuted: [148, 163, 184] as [number, number, number],      // Slate-400
  border: [226, 232, 240] as [number, number, number],         // Slate-200
  bgLight: [248, 250, 252] as [number, number, number],        // Slate-50
  bgSection: [241, 245, 249] as [number, number, number],      // Slate-100
  success: [34, 197, 94] as [number, number, number],          // Green-500
  warning: [234, 179, 8] as [number, number, number],          // Yellow-500
}

// ─── Helpers ─────────────────────────────────────────────────────────

const PAGE_WIDTH = 210 // A4 width in mm
const PAGE_HEIGHT = 297 // A4 height in mm
const MARGIN_LEFT = 20
const MARGIN_RIGHT = 20
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT
const FOOTER_HEIGHT = 20

class PDFBuilder {
  private doc: jsPDF
  private y: number = 0

  constructor() {
    this.doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    this.y = 0
  }

  // ── Page management ──

  private ensureSpace(needed: number): void {
    if (this.y + needed > PAGE_HEIGHT - FOOTER_HEIGHT - 10) {
      this.doc.addPage()
      this.y = 25
      this.drawPageHeader()
    }
  }

  private drawPageHeader(): void {
    // Subtle top bar
    this.doc.setFillColor(...COLORS.primaryDark)
    this.doc.rect(0, 0, PAGE_WIDTH, 3, 'F')

    // Gradient accent line
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.rect(0, 3, PAGE_WIDTH * 0.6, 0.5, 'F')
    this.doc.setFillColor(...COLORS.accentPurple)
    this.doc.rect(PAGE_WIDTH * 0.6, 3, PAGE_WIDTH * 0.4, 0.5, 'F')
  }

  private drawPageFooter(pageNum: number, totalPages: number): void {
    const footerY = PAGE_HEIGHT - 12
    this.doc.setDrawColor(...COLORS.border)
    this.doc.setLineWidth(0.3)
    this.doc.line(MARGIN_LEFT, footerY - 3, PAGE_WIDTH - MARGIN_RIGHT, footerY - 3)

    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(7)
    this.doc.setTextColor(...COLORS.textMuted)
    this.doc.text('Generated by FutureMap — AI-Powered Personalized Learning & Career Guidance Platform', MARGIN_LEFT, footerY)
    this.doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - MARGIN_RIGHT, footerY, { align: 'right' })
  }

  // ── Drawing primitives ──

  private setColor(color: [number, number, number]): void {
    this.doc.setTextColor(...color)
  }

  private drawSectionTitle(text: string, icon?: string): void {
    this.ensureSpace(18)

    // Section divider line
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.rect(MARGIN_LEFT, this.y, 40, 0.8, 'F')
    this.y += 6

    // Title text
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(16)
    this.setColor(COLORS.primaryDark)
    const displayText = icon ? `${icon}  ${text}` : text
    this.doc.text(displayText, MARGIN_LEFT, this.y)
    this.y += 10
  }

  private drawSubsectionTitle(text: string): void {
    this.ensureSpace(12)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(12)
    this.setColor(COLORS.primaryMid)
    this.doc.text(text, MARGIN_LEFT, this.y)
    this.y += 7
  }

  private drawParagraph(text: string, indent: number = 0): void {
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(10)
    this.setColor(COLORS.textSecondary)
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH - indent)
    for (const line of lines) {
      this.ensureSpace(6)
      this.doc.text(line, MARGIN_LEFT + indent, this.y)
      this.y += 5
    }
    this.y += 2
  }

  private drawBullet(text: string, indent: number = 5): void {
    this.ensureSpace(6)
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(10)
    this.setColor(COLORS.textSecondary)

    // Bullet dot
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.circle(MARGIN_LEFT + indent, this.y - 1.2, 1, 'F')

    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH - indent - 6)
    for (let i = 0; i < lines.length; i++) {
      this.doc.text(lines[i], MARGIN_LEFT + indent + 4, this.y)
      this.y += 5
    }
  }

  private drawProgressBar(x: number, y: number, width: number, height: number, percentage: number, label?: string): void {
    // Background track
    this.doc.setFillColor(...COLORS.bgSection)
    this.doc.roundedRect(x, y, width, height, 2, 2, 'F')

    // Filled portion
    const fillWidth = (percentage / 100) * width
    if (percentage > 50) {
      this.doc.setFillColor(...COLORS.success)
    } else if (percentage > 25) {
      this.doc.setFillColor(...COLORS.warning)
    } else {
      this.doc.setFillColor(...COLORS.accentPink)
    }
    if (fillWidth > 0) {
      this.doc.roundedRect(x, y, Math.max(fillWidth, 4), height, 2, 2, 'F')
    }

    // Percentage text
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(8)
    this.setColor(COLORS.primaryDark)
    this.doc.text(`${Math.round(percentage)}%`, x + width + 3, y + height - 1)

    if (label) {
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(8)
      this.setColor(COLORS.textMuted)
      this.doc.text(label, x, y - 2)
    }
  }

  private drawInfoCard(x: number, y: number, w: number, h: number, label: string, value: string, accentColor: [number, number, number]): void {
    // Card background
    this.doc.setFillColor(...COLORS.bgLight)
    this.doc.roundedRect(x, y, w, h, 3, 3, 'F')

    // Left accent bar
    this.doc.setFillColor(...accentColor)
    this.doc.roundedRect(x, y, 2.5, h, 1, 1, 'F')

    // Label
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(8)
    this.setColor(COLORS.textMuted)
    this.doc.text(label, x + 7, y + 8)

    // Value
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(11)
    this.setColor(COLORS.primaryDark)
    const valueLines = this.doc.splitTextToSize(value, w - 12)
    this.doc.text(valueLines[0] || value, x + 7, y + 16)
  }

  // ─── Page Renderers ────────────────────────────────────────────────

  renderCoverPage(data: RoadmapPDFData): void {
    // Full-page dark background
    this.doc.setFillColor(...COLORS.primaryDark)
    this.doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F')

    // Decorative gradient bars at top
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.rect(0, 0, PAGE_WIDTH, 4, 'F')
    this.doc.setFillColor(...COLORS.accentPurple)
    this.doc.rect(0, 4, PAGE_WIDTH, 2, 'F')

    // Decorative circle motifs (simulated low-opacity via lighter color)
    this.doc.setFillColor(34, 45, 62) // Slightly lighter than background for subtle effect
    this.doc.circle(170, 60, 45, 'F')
    this.doc.circle(40, 240, 35, 'F')

    // Logo placeholder — "FM" monogram
    this.y = 55
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.roundedRect(MARGIN_LEFT, this.y, 22, 22, 4, 4, 'F')
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(16)
    this.doc.setTextColor(...COLORS.primaryDark)
    this.doc.text('FM', MARGIN_LEFT + 4.5, this.y + 15)

    // Brand name
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(22)
    this.doc.setTextColor(...COLORS.accentCyan)
    this.doc.text('FutureMap', MARGIN_LEFT + 28, this.y + 15)

    // Main title
    this.y = 110
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(32)
    this.doc.setTextColor(...COLORS.white)
    this.doc.text('Career Roadmap', MARGIN_LEFT, this.y)

    this.y += 14
    this.doc.setFont('helvetica', 'normal')
    this.doc.setFontSize(14)
    this.doc.setTextColor(...COLORS.textMuted)
    this.doc.text('Personalized Learning & Development Plan', MARGIN_LEFT, this.y)

    // Divider
    this.y += 16
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.rect(MARGIN_LEFT, this.y, 50, 1, 'F')

    // Info section
    this.y += 20
    const infoItems = [
      { label: 'Prepared for', value: data.userName || 'Student' },
      { label: 'Target Career', value: data.careerGoal || 'Not specified' },
      { label: 'Current Level', value: (data.currentLevel || 'beginner').charAt(0).toUpperCase() + (data.currentLevel || 'beginner').slice(1) },
      { label: 'Duration', value: `${data.durationMonths || 12} months` },
      { label: 'Generated', value: data.generatedDate || new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) },
    ]

    for (const item of infoItems) {
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(10)
      this.doc.setTextColor(...COLORS.textMuted)
      this.doc.text(`${item.label}:`, MARGIN_LEFT, this.y)

      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(13)
      this.doc.setTextColor(...COLORS.white)
      this.doc.text(item.value, MARGIN_LEFT, this.y + 7)
      this.y += 20
    }

    // Bottom accent
    this.doc.setFillColor(...COLORS.accentPurple)
    this.doc.rect(0, PAGE_HEIGHT - 6, PAGE_WIDTH, 2, 'F')
    this.doc.setFillColor(...COLORS.accentCyan)
    this.doc.rect(0, PAGE_HEIGHT - 4, PAGE_WIDTH, 4, 'F')
  }

  renderExecutiveSummary(data: RoadmapPDFData): void {
    this.doc.addPage()
    this.y = 25
    this.drawPageHeader()

    this.drawSectionTitle('Executive Summary')

    // Summary text
    const summary = data.executiveSummary ||
      `This personalized career roadmap has been designed to guide ${data.userName || 'you'} towards becoming a successful ${data.careerGoal}. ` +
      `Starting from a ${data.currentLevel} level, this ${data.durationMonths}-month plan provides a structured learning path ` +
      `with phased milestones, curated resources, and project recommendations to build practical expertise.`

    this.drawParagraph(summary)
    this.y += 4

    // Quick stats cards
    const cardW = (CONTENT_WIDTH - 10) / 3
    const cardH = 22
    const cardY = this.y

    this.drawInfoCard(MARGIN_LEFT, cardY, cardW, cardH, 'Career Goal', data.careerGoal, COLORS.accentCyan)
    this.drawInfoCard(MARGIN_LEFT + cardW + 5, cardY, cardW, cardH, 'Level', (data.currentLevel || 'Beginner').charAt(0).toUpperCase() + (data.currentLevel || 'Beginner').slice(1), COLORS.accentPurple)
    this.drawInfoCard(MARGIN_LEFT + (cardW + 5) * 2, cardY, cardW, cardH, 'Duration', `${data.durationMonths} months`, COLORS.accentPink)

    this.y = cardY + cardH + 10

    // Phases count
    const totalNodes = data.phases.reduce((sum, p) => sum + (p.nodes?.length || 0), 0)

    const cardW2 = (CONTENT_WIDTH - 10) / 3
    this.drawInfoCard(MARGIN_LEFT, this.y, cardW2, cardH, 'Phases', `${data.phases.length} phases`, COLORS.accentCyan)
    this.drawInfoCard(MARGIN_LEFT + cardW2 + 5, this.y, cardW2, cardH, 'Modules', `${totalNodes} modules`, COLORS.accentPurple)
    this.drawInfoCard(MARGIN_LEFT + (cardW2 + 5) * 2, this.y, cardW2, cardH, 'Progress', `${Math.round(data.progress || 0)}%`, COLORS.success)

    this.y += cardH + 12

    // AI Recommendations
    if (data.aiRecommendations && data.aiRecommendations.length > 0) {
      this.drawSubsectionTitle('AI Recommendations')
      for (const rec of data.aiRecommendations.slice(0, 5)) {
        this.drawBullet(rec)
      }
    }
  }

  renderSkillGapAnalysis(data: RoadmapPDFData): void {
    this.ensureSpace(60)
    this.y += 5
    this.drawSectionTitle('Skill Gap Analysis')

    const currentSkills = data.currentSkills || this.extractSkillsFromPhases(data.phases, 'current')
    const missingSkills = data.missingSkills || this.extractSkillsFromPhases(data.phases, 'missing')
    const readiness = data.readinessScore ?? this.calculateReadiness(currentSkills, missingSkills)

    // Two-column layout
    const colWidth = (CONTENT_WIDTH - 10) / 2

    // Current Skills column
    this.doc.setFillColor(...COLORS.bgLight)
    this.doc.roundedRect(MARGIN_LEFT, this.y, colWidth, 8, 2, 2, 'F')
    this.doc.setFillColor(...COLORS.success)
    this.doc.roundedRect(MARGIN_LEFT, this.y, 3, 8, 1, 1, 'F')
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(10)
    this.setColor(COLORS.primaryDark)
    this.doc.text('Current Skills', MARGIN_LEFT + 7, this.y + 5.5)

    // Missing Skills column
    this.doc.setFillColor(...COLORS.bgLight)
    this.doc.roundedRect(MARGIN_LEFT + colWidth + 10, this.y, colWidth, 8, 2, 2, 'F')
    this.doc.setFillColor(...COLORS.accentPink)
    this.doc.roundedRect(MARGIN_LEFT + colWidth + 10, this.y, 3, 8, 1, 1, 'F')
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(10)
    this.setColor(COLORS.primaryDark)
    this.doc.text('Skills to Acquire', MARGIN_LEFT + colWidth + 17, this.y + 5.5)

    this.y += 14

    const maxItems = Math.max(currentSkills.length, missingSkills.length)
    for (let i = 0; i < Math.min(maxItems, 10); i++) {
      this.ensureSpace(7)
      if (i < currentSkills.length) {
        this.doc.setFillColor(...COLORS.success)
        this.doc.circle(MARGIN_LEFT + 5, this.y - 1.2, 1, 'F')
        this.doc.setFont('helvetica', 'normal')
        this.doc.setFontSize(9)
        this.setColor(COLORS.textSecondary)
        this.doc.text(currentSkills[i], MARGIN_LEFT + 9, this.y)
      }
      if (i < missingSkills.length) {
        this.doc.setFillColor(...COLORS.accentPink)
        this.doc.circle(MARGIN_LEFT + colWidth + 15, this.y - 1.2, 1, 'F')
        this.doc.setFont('helvetica', 'normal')
        this.doc.setFontSize(9)
        this.setColor(COLORS.textSecondary)
        this.doc.text(missingSkills[i], MARGIN_LEFT + colWidth + 19, this.y)
      }
      this.y += 6
    }

    this.y += 6

    // Readiness score bar
    this.drawSubsectionTitle('Career Readiness Score')
    this.drawProgressBar(MARGIN_LEFT, this.y, CONTENT_WIDTH - 20, 6, readiness)
    this.y += 14
  }

  renderLearningRoadmap(data: RoadmapPDFData): void {
    this.ensureSpace(30)
    this.drawSectionTitle('Learning Roadmap')

    const phases: PDFPhase[] = Array.isArray(data.phases) ? data.phases : Object.values(data.phases || {}) as PDFPhase[]

    phases.forEach((phase, index) => {
      this.ensureSpace(40)

      // Phase header card
      const phaseColors: [number, number, number][] = [COLORS.accentCyan, COLORS.accentPurple, COLORS.accentPink, COLORS.success]
      const color = phaseColors[index % phaseColors.length]

      // Phase number badge
      this.doc.setFillColor(...color)
      this.doc.roundedRect(MARGIN_LEFT, this.y, 8, 8, 2, 2, 'F')
      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(10)
      this.doc.setTextColor(...COLORS.white)
      this.doc.text(`${index + 1}`, MARGIN_LEFT + 2.7, this.y + 5.8)

      // Phase title
      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(13)
      this.setColor(COLORS.primaryDark)
      this.doc.text(phase.title || `Phase ${index + 1}`, MARGIN_LEFT + 12, this.y + 5.5)

      // Duration badge
      const durationText = typeof phase.duration === 'number' ? `${phase.duration} weeks` : (phase.duration || '')
      if (durationText) {
        this.doc.setFont('helvetica', 'normal')
        this.doc.setFontSize(8)
        this.setColor(COLORS.textMuted)
        const durationWidth = this.doc.getTextWidth(durationText) + 6
        this.doc.setFillColor(...COLORS.bgSection)
        this.doc.roundedRect(PAGE_WIDTH - MARGIN_RIGHT - durationWidth, this.y + 1, durationWidth, 6, 2, 2, 'F')
        this.doc.text(durationText, PAGE_WIDTH - MARGIN_RIGHT - durationWidth + 3, this.y + 5)
      }

      this.y += 12

      // Phase description
      if (phase.description) {
        this.drawParagraph(phase.description, 4)
      }

      // Phase nodes/items
      if (phase.nodes && phase.nodes.length > 0) {
        for (const node of phase.nodes.slice(0, 8)) {
          this.ensureSpace(8)

          // Node type icon
          const typeIcon = node.type === 'project' ? '◆' : node.type === 'certification' ? '★' : '●'
          this.doc.setFont('helvetica', 'normal')
          this.doc.setFontSize(8)
          this.setColor(color)
          this.doc.text(typeIcon, MARGIN_LEFT + 8, this.y)

          // Node title
          this.doc.setFont('helvetica', 'normal')
          this.doc.setFontSize(9)
          this.setColor(COLORS.textPrimary)
          this.doc.text(node.title, MARGIN_LEFT + 14, this.y)

          // Duration/difficulty on the right
          if (node.difficulty || node.duration) {
            const meta = [node.difficulty, node.duration].filter(Boolean).join(' · ')
            this.doc.setFont('helvetica', 'normal')
            this.doc.setFontSize(7)
            this.setColor(COLORS.textMuted)
            this.doc.text(meta, PAGE_WIDTH - MARGIN_RIGHT, this.y, { align: 'right' })
          }

          this.y += 6
        }

        if (phase.nodes.length > 8) {
          this.doc.setFont('helvetica', 'italic')
          this.doc.setFontSize(8)
          this.setColor(COLORS.textMuted)
          this.doc.text(`+ ${phase.nodes.length - 8} more items...`, MARGIN_LEFT + 14, this.y)
          this.y += 6
        }
      }

      // Connecting line to next phase
      if (index < phases.length - 1) {
        this.y += 2
        this.doc.setDrawColor(...COLORS.border)
        this.doc.setLineWidth(0.3)
        this.doc.setLineDashPattern([2, 2], 0)
        this.doc.line(MARGIN_LEFT + 4, this.y, MARGIN_LEFT + 4, this.y + 8)
        this.doc.setLineDashPattern([], 0)
        this.y += 10
      } else {
        this.y += 6
      }
    })
  }

  renderRecommendedResources(data: RoadmapPDFData): void {
    const resources = data.recommendedResources || this.extractResourcesFromPhases(data.phases)
    if (resources.length === 0) return

    this.ensureSpace(30)
    this.drawSectionTitle('Recommended Resources')

    // Table header
    const cols = [
      { label: 'Resource', x: MARGIN_LEFT, w: 65 },
      { label: 'Platform', x: MARGIN_LEFT + 65, w: 40 },
      { label: 'Difficulty', x: MARGIN_LEFT + 105, w: 35 },
      { label: 'Duration', x: MARGIN_LEFT + 140, w: 30 },
    ]

    this.doc.setFillColor(...COLORS.primaryDark)
    this.doc.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, 8, 1, 1, 'F')

    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(8)
    this.doc.setTextColor(...COLORS.white)
    for (const col of cols) {
      this.doc.text(col.label, col.x + 2, this.y + 5.5)
    }
    this.y += 10

    // Table rows
    for (let i = 0; i < Math.min(resources.length, 12); i++) {
      this.ensureSpace(9)
      const r = resources[i]

      if (i % 2 === 0) {
        this.doc.setFillColor(...COLORS.bgLight)
        this.doc.rect(MARGIN_LEFT, this.y - 3, CONTENT_WIDTH, 7, 'F')
      }

      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(8)
      this.setColor(COLORS.textPrimary)
      this.doc.text(this.truncate(r.name, 35), cols[0].x + 2, this.y)
      this.setColor(COLORS.textSecondary)
      this.doc.text(this.truncate(r.platform, 20), cols[1].x + 2, this.y)
      this.doc.text(r.difficulty || '-', cols[2].x + 2, this.y)
      this.doc.text(r.duration || '-', cols[3].x + 2, this.y)
      this.y += 7
    }

    this.y += 5
  }

  renderProjectRecommendations(data: RoadmapPDFData): void {
    const groups = data.projectRecommendations || this.extractProjectsFromPhases(data.phases)
    if (groups.length === 0) return

    this.ensureSpace(30)
    this.drawSectionTitle('Project Recommendations')

    for (const group of groups) {
      this.ensureSpace(15)
      this.drawSubsectionTitle(group.level)

      for (const project of group.projects.slice(0, 5)) {
        this.drawBullet(project, 8)
      }
      this.y += 3
    }
  }

  renderCareerOpportunities(data: RoadmapPDFData): void {
    const opportunities = data.careerOpportunities || this.getDefaultOpportunities(data.careerGoal)
    if (opportunities.length === 0) return

    this.ensureSpace(30)
    this.drawSectionTitle('Career Opportunities')

    for (const opp of opportunities.slice(0, 6)) {
      this.ensureSpace(25)

      // Role card
      this.doc.setFillColor(...COLORS.bgLight)
      this.doc.roundedRect(MARGIN_LEFT, this.y, CONTENT_WIDTH, 18, 2, 2, 'F')

      // Left accent
      this.doc.setFillColor(...COLORS.accentPurple)
      this.doc.roundedRect(MARGIN_LEFT, this.y, 2.5, 18, 1, 1, 'F')

      // Role name
      this.doc.setFont('helvetica', 'bold')
      this.doc.setFontSize(10)
      this.setColor(COLORS.primaryDark)
      this.doc.text(opp.role, MARGIN_LEFT + 7, this.y + 7)

      // Details
      this.doc.setFont('helvetica', 'normal')
      this.doc.setFontSize(8)
      this.setColor(COLORS.textSecondary)
      const details = [
        opp.salaryRange ? `Salary: ${opp.salaryRange}` : null,
        opp.demand ? `Demand: ${opp.demand}` : null,
        opp.growth ? `Growth: ${opp.growth}` : null,
      ].filter(Boolean).join('  |  ')
      this.doc.text(details, MARGIN_LEFT + 7, this.y + 13)

      this.y += 22
    }
  }

  // ─── Build ─────────────────────────────────────────────────────────

  build(data: RoadmapPDFData): ArrayBuffer {
    // 1. Cover Page
    this.renderCoverPage(data)

    // 2. Executive Summary
    this.renderExecutiveSummary(data)

    // 3. Skill Gap Analysis
    this.renderSkillGapAnalysis(data)

    // 4. Learning Roadmap Timeline
    this.renderLearningRoadmap(data)

    // 5. Recommended Resources
    this.renderRecommendedResources(data)

    // 6. Project Recommendations
    this.renderProjectRecommendations(data)

    // 7. Career Opportunities
    this.renderCareerOpportunities(data)

    // Add page footers to all pages
    const totalPages = this.doc.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i)
      if (i > 1) { // skip footer on cover page
        this.drawPageFooter(i - 1, totalPages - 1)
      }
    }

    return this.doc.output('arraybuffer')
  }

  // ─── Data Extraction Helpers ───────────────────────────────────────

  private extractSkillsFromPhases(phases: PDFPhase[], type: 'current' | 'missing'): string[] {
    const allSkills: string[] = []
    const phaseArr: PDFPhase[] = Array.isArray(phases) ? phases : Object.values(phases || {}) as PDFPhase[]

    for (const phase of phaseArr) {
      if (phase.nodes) {
        for (const node of phase.nodes) {
          if (node.skills) {
            allSkills.push(...node.skills)
          }
          if (node.title) {
            allSkills.push(node.title)
          }
        }
      }
    }

    const unique = Array.from(new Set(allSkills))
    if (type === 'current') {
      return unique.slice(0, Math.ceil(unique.length * 0.3))
    }
    return unique.slice(Math.ceil(unique.length * 0.3))
  }

  private calculateReadiness(current: string[], missing: string[]): number {
    const total = current.length + missing.length
    if (total === 0) return 50
    return Math.round((current.length / total) * 100)
  }

  private extractResourcesFromPhases(phases: PDFPhase[]): PDFResource[] {
    const resources: PDFResource[] = []
    const phaseArr: PDFPhase[] = Array.isArray(phases) ? phases : Object.values(phases || {}) as PDFPhase[]

    for (const phase of phaseArr) {
      if (phase.nodes) {
        for (const node of phase.nodes) {
          if (node.resources && node.resources.length > 0) {
            for (const res of node.resources) {
              resources.push({
                name: typeof res === 'string' ? res : (res as any).name || 'Resource',
                platform: typeof res === 'string' ? 'Online' : (res as any).platform || 'Online',
                difficulty: node.difficulty || 'Intermediate',
                duration: node.duration || 'Self-paced',
              })
            }
          } else if (node.type === 'course') {
            resources.push({
              name: node.title,
              platform: 'Online',
              difficulty: node.difficulty || 'Intermediate',
              duration: node.duration || 'Self-paced',
            })
          }
        }
      }
    }
    return resources.slice(0, 15)
  }

  private extractProjectsFromPhases(phases: PDFPhase[]): PDFProjectGroup[] {
    const projects: { beginner: string[], intermediate: string[], advanced: string[] } = {
      beginner: [], intermediate: [], advanced: []
    }
    const phaseArr: PDFPhase[] = Array.isArray(phases) ? phases : Object.values(phases || {}) as PDFPhase[]

    for (const phase of phaseArr) {
      if (phase.nodes) {
        for (const node of phase.nodes) {
          if (node.type === 'project') {
            const diff = node.difficulty || 'intermediate'
            if (diff in projects) {
              projects[diff as keyof typeof projects].push(node.title)
            }
          }
        }
      }
    }

    const groups: PDFProjectGroup[] = []
    if (projects.beginner.length > 0) groups.push({ level: 'Beginner Projects', projects: projects.beginner })
    if (projects.intermediate.length > 0) groups.push({ level: 'Intermediate Projects', projects: projects.intermediate })
    if (projects.advanced.length > 0) groups.push({ level: 'Advanced Projects', projects: projects.advanced })

    // If no projects found, generate generic ones
    if (groups.length === 0) {
      groups.push(
        { level: 'Beginner Projects', projects: ['Portfolio Website', 'Calculator App', 'Todo List Application'] },
        { level: 'Intermediate Projects', projects: ['Full-Stack CRUD App', 'REST API Development', 'Data Dashboard'] },
        { level: 'Advanced Projects', projects: ['AI-Powered Application', 'Real-time Chat System', 'Open Source Contribution'] },
      )
    }

    return groups
  }

  private getDefaultOpportunities(careerGoal: string): PDFCareerOpportunity[] {
    return [
      { role: `Junior ${careerGoal}`, salaryRange: '₹4-8 LPA', demand: 'High', growth: 'Strong' },
      { role: `${careerGoal}`, salaryRange: '₹8-15 LPA', demand: 'Very High', growth: 'Excellent' },
      { role: `Senior ${careerGoal}`, salaryRange: '₹15-30 LPA', demand: 'High', growth: 'Excellent' },
      { role: `Lead ${careerGoal}`, salaryRange: '₹25-45 LPA', demand: 'Moderate', growth: 'Strong' },
    ]
  }

  private truncate(text: string, maxLen: number): string {
    if (text.length <= maxLen) return text
    return text.substring(0, maxLen - 2) + '...'
  }
}

// ─── Public API ──────────────────────────────────────────────────────

export function generateRoadmapPDF(data: RoadmapPDFData): ArrayBuffer {
  const builder = new PDFBuilder()
  return builder.build(data)
}
